FROM golang:1.4
MAINTAINER Maxime Horcholle <maxime.horcholle@gmail.com>

RUN go get gopkg.in/mgo.v2
RUN go get github.com/garyburd/redigo/redis
RUN go get github.com/spf13/viper
RUN go get github.com/julienschmidt/httprouter
RUN go get github.com/nfnt/resize
RUN go get github.com/Sirupsen/logrus
RUN go get github.com/asaskevich/govalidator
RUN go get gopkg.in/olivere/elastic.v2
RUN go get github.com/codegangsta/cli
